// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddtableAdminLogins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtableAdminLogins));
        
        string IMigrationMetadata.Id
        {
            get { return "202307040601313_Add-table-AdminLogins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
